stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
      - src/data/data_ingestion.py
      - data/reddit.csv
    params:
      - data_ingestion.test_size
    outs:
      - data/raw 
  
  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
      - src/data/data_preprocessing.py
      - src/common/text_preprocessing.py
      - data/raw/test.csv
      - data/raw/train.csv
    outs:
      - data/interim

  model_building:
    cmd: python src/model/model_building.py 
    deps:
      - src/model/model_building.py
      - src/model/pipeline.py
      - src/common/text_preprocessing.py
      - data/interim/train_processed.csv
    params:
      - model_building.max_features
      - model_building.ngram_range 
      - model_building.learning_rate
      - model_building.max_depth
      - model_building.n_estimators
    outs: 
      - sentiment_pipeline.pkl
    
  model_evaluation:
    cmd: python src/model/model_evaluation.py 
    deps:
      - src/model/model_evaluation.py
      - src/model/config.py
      - src/common/text_preprocessing.py
      - sentiment_pipeline.pkl
      - data/interim/train_processed.csv
      - data/interim/test_processed.csv
    outs:
      - experiment_info.json
  
  model_registration:
    cmd: python src/model/register_model.py 
    deps: 
    - experiment_info.json
    - src/model/register_model.py
    - src/model/config.py
